services:
  api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./backend/src:/usr/src/app/src

  web:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    volumes:
      - ./frontend/src:/usr/src/app/src
      - /app/node_modules
